### ISSUE TITLE
[Question] Abgrenzung Contao 4.4 zu >= 4.5

### ISSUE THREAD

**Issue by FunkeMT** [Sioweb/Contao4DummyBundle#3]
Besten Dank für die Bereitstellung des Dummy-Bundles sowie für die Erklärungen und Hinweise.

Mir ist jedoch noch nicht ganz klar, an welchen Stellen nun genau die Abgrenzung von Contao 4.4 zu den neueren Versionen >= 4.5 stattfindet, da ich im Moment nur mit der LTS Version 4.4 arbeiten kann.

Laut der Readme gibt es essentielle Unterschiede bei den Hooks, Events und der `src/Resources/contao/config/config.php` Datei.
Zusätzlich ist in der Datei beschrieben, dass unter 4.4 diese `config.php` notwendig ist.
Können aber nun dennoch die Events und Hooks verwendet werden, so wie sie in deinem Bundle verwendet werden?
Ist der einzige Unterschied tatsächlich nur diese eine `src/Resources/contao/config/config.php` Datei, oder ist man nun in Funktionalität etc. eingeschränkt?

Zusätzlich ist mir nicht ganz klar, welche Aufgabe die Klasse `src/Dca/Dummy.php` inne hat. Ist dies nur eine Auslagerung der früheren Konfiguration unter `src/Resources/contao/dca/tl_dummy.php`?

Weitere Frage zu Doctrine: Wie und zu welchem Zeitpunkt werden die Datenbank Tabellen angelegt (also in dem DummyBundle Fall die Tabelle `tl_dummy`)? Muss die Tabelle händisch angelegt werden? Muss weiterhin das `/contao/install`-Tool aufgerufen werden? Wird die Entity `src/Entity/Dummy.php` über ein Doctrine über die Symfony Console generiert?

Generelle Frage: Ich verstehe es so, dass dein Bundle ebenso ein Contao Backend-Modul darstellt? Wenn ich dein Bundle in meine Contao Installation einhänge, sehe ich jedoch keinen neuen Navigationspunkt in der Contao Seitenleiste. Die DB-Änderungen wurden erfolgreich vom Install Tool durchgeführt, und die API ist auch über `dummybundle/api/all` erreichbar. Müssen für das Backend-Modul noch separate Einstellungen getätigt werden?

Besten Dank!

**Comment by Sioweb** [comment]
Ho!

ich habe gar keine Nachricht über dieses Issue bekommen - sonst hätte ich früher geantwortet.

Sind die Fragen noch aktuell?

**Comment by FunkeMT** [comment]
Hi,
hat sich tatsächlich inzwischen erledigt.
Dennoch besten Dank!
